run:
  generations: 1

plugins:
  extended_detectors: false
  probe_spec: promptinject
  probes:
    promptinject:
      max_prompts: 1




reporting:
    report_prefix: run_output
    report_dir: /home/mwm/repositories/GBI/ml-checker/runner
